try {
	throw {name: 4342}
} catch (error) {
	console.log(error)
}